name: Manage PRs modifying .github directory

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  manage-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check for changes in .github directory
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q '^.github/'; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: check
        run: |
          echo "잘 나옴?"
          echo git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          echo ${{ env.changes_detected }}
        
      - name: Comment and close PR if unauthorized changes detected
        if: ${{ env.changes_detected == 'true' }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --reject --body "This PR modifies files in the .github directory, which is not allowed. Please remove these changes."
          gh pr comment ${{ github.event.pull_request.number }} --body "This PR modifies files in the .github directory, which is not allowed. Closing the PR automatically."
          gh pr close ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
