name: Manage PRs modifying .github directory

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  manage-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch all branches
        run: git fetch
      
      - name: Get changed files
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
          echo "Comparing $BASE_BRANCH with $HEAD_BRANCH"
          # Ensure we are on the HEAD branch
          git checkout $HEAD_BRANCH
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH $HEAD_BRANCH)
          echo "Changed Files: $CHANGED_FILES"
        shell: bash
        
      - name: Check for changes in .github directory
        id: check_changes
        run: |
          if git diff --name-only ${{ origin/github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} | grep -q '^.github/'; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi
          
      - name: Get changed files
        run: |
          echo env.changes_detected
