name: Create Pull Request

on:
  push:
    branches-ignore:
     - 'master'     # master 브랜치는 제외
     - 'main'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: echo "${{ secrets.USER_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          BASE_BRANCH="master"
          HEAD_BRANCH=$(git symbolic-ref --short HEAD)

          echo $BASE_BRANCH
          echo $MASTER_BRANCH
          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head $HEAD_BRANCH --base $BASE_BRANCH --state open --json number --jq '.[0].number')

          if [ -z "$PR_EXISTS" ]; then
            gh pr create --base $BASE_BRANCH --head $HEAD_BRANCH --title "Automated PR from $HEAD_BRANCH" --body "This is an automated PR created from branch $HEAD_BRANCH."
          else
            echo "PR already exists: $PR_EXISTS"
          fi
